dist: trusty
language: node_js
sudo: required
node_js:
  - '8.3.0'

addons:
  chrome: stable
apt:
  packages:
    - testrpc

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - testrpc

before_script:
- npm install -g @angular/cli
- npm install
- ng build

script:
- ng e2e
